from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Statisctic(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(951, 708)
        MainWindow.setStyleSheet("QMainWindow {\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 183, 197, 255), stop:1 rgba(255, 255, 204, 255));\n"
"    border-radius: 15px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 341, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 90, 431, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 170, 431, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 250, 601, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(560, 350, 381, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(20, 350, 371, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.list_top_book = QtWidgets.QListWidget(self.centralwidget)
        self.list_top_book.setGeometry(QtCore.QRect(20, 420, 361, 251))
        self.list_top_book.setObjectName("list_top_book")
        self.list_top_readers = QtWidgets.QListWidget(self.centralwidget)
        self.list_top_readers.setGeometry(QtCore.QRect(570, 420, 361, 251))
        self.list_top_readers.setObjectName("list_top_readers")
        self.sum_book = QtWidgets.QLabel(self.centralwidget)
        self.sum_book.setGeometry(QtCore.QRect(370, 10, 91, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.sum_book.setFont(font)
        self.sum_book.setObjectName("sum_book")
        self.sum_readers = QtWidgets.QLabel(self.centralwidget)
        self.sum_readers.setGeometry(QtCore.QRect(450, 90, 91, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.sum_readers.setFont(font)
        self.sum_readers.setObjectName("sum_readers")
        self.sum_extradition = QtWidgets.QLabel(self.centralwidget)
        self.sum_extradition.setGeometry(QtCore.QRect(420, 170, 91, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.sum_extradition.setFont(font)
        self.sum_extradition.setObjectName("sum_extradition")
        self.sum_book_to_extradition = QtWidgets.QLabel(self.centralwidget)
        self.sum_book_to_extradition.setGeometry(QtCore.QRect(590, 250, 91, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.sum_book_to_extradition.setFont(font)
        self.sum_book_to_extradition.setObjectName("sum_book_to_extradition")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 951, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Статистика"))
        self.label.setText(_translate("MainWindow", "Общее количество книг:"))
        self.label_2.setText(_translate("MainWindow", "Общее количество читателей:"))
        self.label_3.setText(_translate("MainWindow", "Количество выданных книг:"))
        self.label_4.setText(_translate("MainWindow", "Количество книг доступных для выдачи:"))
        self.label_5.setText(_translate("MainWindow", "Самые активные читатели:"))
        self.label_6.setText(_translate("MainWindow", "Самые популярные книги:"))
        self.sum_book.setText(_translate("MainWindow", "999"))
        self.sum_readers.setText(_translate("MainWindow", "999"))
        self.sum_extradition.setText(_translate("MainWindow", "999"))
        self.sum_book_to_extradition.setText(_translate("MainWindow", "999"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_Statisctic()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
